# Generated by Django 5.2.7 on 2026-06-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0010_purchaseorder_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='cogs_ratio_forecast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
