# Generated by Django 5.2.7 on 2026-06-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0011_add_cogs_ratio_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='avg_sales_7d',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
