# Generated by Django 5.2.7 on 2026-06-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0012_purchaseorderdetail_avg_sales_7d'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='forecast_shipping_fee_per_cbm',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
