# Generated by Django 5.2.7 on 2026-06-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_supplier_and_product_variant_supplier'),
        ('purchasing', '0013_purchaseorder_forecast_shipping_fee_per_cbm'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.supplier'),
        ),
    ]
