# Generated by Django 5.2.7 on 2026-06-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0014_add_supplier_fk_to_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='has_discount',
            field=models.BooleanField(default=False),
        ),
    ]
