# Generated by Django 5.2.7 on 2026-06-27 08:10

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile'),
        ('inventory', '0022_productvariant_last_discounted_unit_price_foreign'),
        ('purchasing', '0016_per_company_po_number_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingPool',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='sourcing_pool_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_pools', to='inventory.supplier')),
            ],
            options={
                'unique_together': {('company', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='SourcingPoolItem',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='sourcing_pool_item_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('qty_suggested', models.IntegerField(blank=True, null=True)),
                ('supplier_link', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_file', models.FileField(blank=True, null=True, upload_to='sourcing/images/')),
                ('image_download_status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('times_ordered', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_items', to='inventory.category')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.sourcingpool')),
            ],
            options={
                'unique_together': {('pool', 'product_name', 'variant_name')},
            },
        ),
    ]
