# Generated by Django 5.2.7 on 2026-06-27 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_productvariant_last_discounted_unit_price_foreign'),
        ('purchasing', '0017_sourcingpool_sourcingpoolitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='draft_product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='sourcing_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_details', to='purchasing.sourcingpoolitem'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant'),
        ),
    ]
