# Generated by Django 5.2.7 on 2026-06-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_productvariant_last_discounted_unit_price_foreign'),
        ('purchasing', '0018_purchaseorderdetail_draft_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingpoolitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_items', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='sourcingpoolitem',
            name='variant_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
