# Generated by Django 5.2.7 on 2026-06-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile'),
        ('inventory', '0023_product_dim1_key_product_dim1_options_and_more'),
        ('purchasing', '0019_sourcingpoolitem_variant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sourcingpoolitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sourcingpoolitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='sourcingpoolitem',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_link__isnull', False)), fields=('pool', 'supplier_link', 'variant_name'), name='unique_pool_supplier_link_variant'),
        ),
        migrations.AddConstraint(
            model_name='sourcingpoolitem',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_link__isnull', True)), fields=('pool', 'product_name', 'variant_name'), name='unique_pool_product_name_variant'),
        ),
    ]
