# Generated by Django 5.2.7 on 2026-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile'),
        ('inventory', '0023_product_dim1_key_product_dim1_options_and_more'),
        ('purchasing', '0020_alter_sourcingpoolitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sourcingpoolitem',
            name='unique_pool_supplier_link_variant',
        ),
        migrations.RemoveConstraint(
            model_name='sourcingpoolitem',
            name='unique_pool_product_name_variant',
        ),
        migrations.AddConstraint(
            model_name='sourcingpoolitem',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_link__isnull', False), models.Q(('supplier_link', ''), _negated=True)), fields=('pool', 'supplier_link', 'variant_name'), name='unique_pool_supplier_link_variant'),
        ),
        migrations.AddConstraint(
            model_name='sourcingpoolitem',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_link__isnull', True), ('supplier_link', ''), _connector='OR'), fields=('pool', 'product_name', 'variant_name'), name='unique_pool_product_name_variant'),
        ),
    ]
