# Generated by Django 5.2.7 on 2026-07-07 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0023_sourcingpoolitem_dim_fields_colorabbreviation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourcingpoolitem",
            name="pool",
        ),
        migrations.RemoveField(
            model_name="sourcingpoolitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="sourcingpoolitem",
            name="company",
        ),
        migrations.RemoveField(
            model_name="sourcingpoolitem",
            name="used_in_po",
        ),
        migrations.RemoveField(
            model_name="sourcingpoolitem",
            name="variant",
        ),
        migrations.DeleteModel(
            name="SourcingPool",
        ),
        migrations.DeleteModel(
            name="SourcingPoolItem",
        ),
    ]
