# Generated by Django 5.2.7 on 2026-07-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_noop_fk_refs"),
        ("purchasing", "0024_remove_sourcingpoolitem_pool_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="purchaseorderdetail",
                    name="product_variant",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.productvariant",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
