# Generated by Django 5.2.7 on 2026-08-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0026_add_supplier_productsupplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="commission_fee",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="forecast_shipping_fee",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="forecast_shipping_fee_per_cbm",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="procure_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="refund_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="shipping_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="shipping_fee_per_cbm",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_item_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_order_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderdetail",
            name="discounted_total_price_base",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderdetail",
            name="discounted_unit_price_base",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderdetail",
            name="total_price_base",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderdetail",
            name="unit_price_base",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
