# Generated by Django 5.2.7 on 2026-07-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_noop_fk_refs"),
        ("sales", "0003_salesorder_source_platform"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="salesorderitem",
                    name="product_variant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.productvariant",
                    ),
                ),
                migrations.AlterField(
                    model_name="salesreturnitem",
                    name="product_variant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.productvariant",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
