# Generated by Django 5.2.7 on 2026-07-08 21:00
# Ensures catalog table renames are applied before sales FK constraints that reference them

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_noop_fk_refs"),
        ("catalog", "0003_rename_master_tables"),
    ]

    operations = []
