# Generated by Django 5.2.7 on 2026-08-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0006_noop_fk_refs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="gross_profit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="net_revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="shipping_fee_seller",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="total_cogs",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="total_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="total_marketplace_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesordercogsdetail",
            name="cogs_per_unit",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesordercogsdetail",
            name="total_cogs",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="actual_cogs_per_unit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="actual_cogs_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="commission_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="line_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="service_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="total_marketplace_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesreturn",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="salesreturnitem",
            name="reversed_cogs_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
