x-db-name: &db_name mini_erp
x-db-user: &db_user postgres
x-db-password: &db_password postgres

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: *db_name
      POSTGRES_USER: *db_user
      POSTGRES_PASSWORD: *db_password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mini_erp" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  migrate:
    container_name: migration
    volumes:
      - .:/app
      - /app/.venv
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: *db_name
      DB_USER: *db_user
      DB_PASSWORD: *db_password
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    entrypoint: [ "bash", "/app/entrypoint.sh" ]

volumes:
  postgres_data:
