[mypy]
# -------------------------
#  Project scanning
# -------------------------
files = apps/, core/
exclude = (^.*(/migrations/|/__init__\.py|/test_.*\.py|/tests\.py)$)|(^scripts/)

# -------------------------
#  General typing behavior
# -------------------------
python_version = 3.12
explicit_package_bases = True
ignore_missing_imports = True

# Strictness
warn_return_any = True
disallow_untyped_calls = True
disallow_untyped_defs = True
check_untyped_defs = True
disallow_incomplete_defs = False

# Cosmetic / readability
pretty = True
show_error_codes = True
disable_error_code = var-annotated

# -------------------------
#  Plugins
# -------------------------
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = core.settings

# -------------------------
#  Third-party ignores
# -------------------------
[mypy-requests.*]
ignore_missing_imports = True

[mypy-dateutil.*]
ignore_missing_imports = True
