# Generated by Django 5.2.7 on 2026-05-27 07:03

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile'),
        ('finance', '0002_add_expense_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='cash_transaction_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('transaction_type', models.CharField(choices=[('INFLOW', 'Inflow'), ('OUTFLOW', 'Outflow')], max_length=10)),
                ('category', models.CharField(choices=[('SALES_SETTLEMENT', 'Sales Settlement (Marketplace Withdrawal)'), ('EQUITY_INJECTION', 'Equity Injection'), ('FOUNDER_LOAN', 'Founder Loan'), ('BANK_INTEREST', 'Bank Interest'), ('SUPPLIER_REFUND', 'Supplier Refund'), ('OTHER_INCOME', 'Other Income'), ('OTHER_EXPENSE', 'Other Expense / Miscellaneous')], max_length=30)),
                ('reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'ordering': ['-transaction_date', '-cdate'],
                'indexes': [models.Index(fields=['transaction_date'], name='finance_cas_transac_5e36ba_idx'), models.Index(fields=['transaction_type', 'category'], name='finance_cas_transac_be5409_idx')],
            },
        ),
    ]
