# Generated by Django 5.2.7 on 2026-08-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_add_cash_transaction_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountspayable",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="accountspayable",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="accountsreceivable",
            name="expected_amount",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="accountsreceivable",
            name="settled_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="cashtransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
