# Generated by Django 5.2.7 on 2026-05-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_category_shopee_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcogs',
            name='allocated_commission_fee',
            field=models.BigIntegerField(default=0, help_text='Commission fee allocated per item total (IDR)'),
        ),
    ]
