# Generated by Django 5.2.7 on 2026-06-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_variant_sku_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
