# Generated by Django 5.2.7 on 2026-06-08 11:16

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile'),
        ('inventory', '0011_add_supplier_link_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='supplier_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantSupplier',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_variant_supplier_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('supplier_link', models.URLField(blank=True, help_text="URL to this product on the supplier's site", max_length=500, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary supplier for this variant')),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_suppliers', to='inventory.productvariant')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_suppliers', to='inventory.supplier')),
            ],
            options={
                'unique_together': {('product_variant', 'supplier')},
            },
        ),
    ]
