# Generated by Django 5.2.7 on 2026-06-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_supplier_and_product_variant_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
