# Generated by Django 5.2.7 on 2026-06-09 15:07

import re

from django.db import migrations


def _slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower().strip()).strip("-") or "default"


def migrate_forward(apps, schema_editor):
    Product = apps.get_model("inventory", "Product")
    ProductVariant = apps.get_model("inventory", "ProductVariant")

    for product in Product.objects.all():
        old_opts = product.variant_options
        if not isinstance(old_opts, list) or not old_opts:
            continue

        first = old_opts[0] if old_opts else {}
        if isinstance(first, dict) and "id" in first:
            continue

        order_to_id: dict[str, str] = {}
        new_opts: list[dict] = []
        for opt in old_opts:
            name = opt.get("name", "")
            order = opt.get("order", 1)
            opt_id = _slugify(name)
            order_to_id[str(order)] = opt_id
            new_opts.append({"id": opt_id, "name": name, "order": order, "values": []})

        opt_value_map: dict[str, dict[str, str]] = {o["id"]: {} for o in new_opts}
        for variant in ProductVariant.objects.filter(product=product):
            vv = variant.variant_values
            if not isinstance(vv, dict):
                continue
            for order_str, label in vv.items():
                opt_id = order_to_id.get(order_str)
                if opt_id and label:
                    val_id = _slugify(str(label))
                    opt_value_map[opt_id][val_id] = str(label)

        for opt in old_opts:
            order = opt.get("order", 1)
            opt_id = order_to_id.get(str(order))
            if opt_id:
                for label in opt.get("values") or []:
                    if isinstance(label, str) and label:
                        val_id = _slugify(label)
                        opt_value_map[opt_id].setdefault(val_id, label)

        for opt in new_opts:
            val_dict = opt_value_map[opt["id"]]
            opt["values"] = [{"id": vid, "label": lbl} for vid, lbl in val_dict.items()]

        for variant in ProductVariant.objects.filter(product=product):
            vv = variant.variant_values
            if not isinstance(vv, dict):
                continue
            new_vv: dict[str, str] = {}
            for order_str, label in vv.items():
                opt_id = order_to_id.get(order_str)
                if opt_id and label:
                    new_vv[opt_id] = _slugify(str(label))
            variant.variant_values = new_vv
            variant.save(update_fields=["variant_values"])

        product.variant_options = new_opts
        product.save(update_fields=["variant_options"])


def migrate_backward(apps, schema_editor):
    pass


def _update_trigger_forward(apps, schema_editor):
    schema_editor.execute("""
    CREATE OR REPLACE FUNCTION generate_variant_sku()
    RETURNS TRIGGER AS $$
    DECLARE
        parent_sku TEXT;
        sku_suffix TEXT;
    BEGIN
        IF NEW.sku_variant_code IS NULL OR NEW.sku_variant_code = '' THEN
            SELECT sku_code INTO parent_sku
            FROM inventory_product WHERE product_id = NEW.product_id;

            NEW.sku_variant_code := parent_sku;

            SELECT string_agg(UPPER(value), '-' ORDER BY key) INTO sku_suffix
            FROM jsonb_each_text(NEW.variant_values::jsonb);

            IF sku_suffix IS NOT NULL AND sku_suffix != '' THEN
                NEW.sku_variant_code := NEW.sku_variant_code || '-' || sku_suffix;
            END IF;
        END IF;

        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)


def _update_trigger_backward(apps, schema_editor):
    schema_editor.execute("""
    CREATE OR REPLACE FUNCTION generate_variant_sku()
    RETURNS TRIGGER AS $$
    DECLARE
        parent_sku TEXT;
        val1 TEXT;
        val2 TEXT;
    BEGIN
        IF NEW.sku_variant_code IS NULL OR NEW.sku_variant_code = '' THEN
            SELECT sku_code INTO parent_sku
            FROM inventory_product WHERE product_id = NEW.product_id;

            val1 := NEW.variant_values->>'1';
            val2 := NEW.variant_values->>'2';

            NEW.sku_variant_code := parent_sku;

            IF val1 IS NOT NULL AND val1 != '' THEN
                NEW.sku_variant_code := NEW.sku_variant_code || '-' || UPPER(val1);
            END IF;

            IF val2 IS NOT NULL AND val2 != '' THEN
                NEW.sku_variant_code := NEW.sku_variant_code || '-' || UPPER(val2);
            END IF;
        END IF;

        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_add_supplier_link_to_supplier"),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
        migrations.RunPython(_update_trigger_forward, _update_trigger_backward),
    ]
