# Generated by Django 5.2.7 on 2026-06-10 10:24

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile'),
        ('inventory', '0014_migrate_variant_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier_link',
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_supplier_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('supplier_link', models.URLField(blank=True, help_text="URL to this product on the supplier's site", max_length=500, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='inventory.supplier')),
            ],
            options={
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
