# Generated by Django 5.2.7 on 2026-06-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_product_supplier_link_productsupplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariantSupplier',
        ),
    ]
