# Generated by Django 5.2.7 on 2026-06-12 15:13

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile'),
        ('inventory', '0017_businessentity_productbusinessentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMarketplace',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='company_marketplace_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='businessentity',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_entities', to='inventory.companymarketplace'),
        ),
    ]
