# Generated by Django 5.2.7 on 2026-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_companymarketplace_update_businessentity_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PUR', 'Purchase Order'), ('IN', 'Inbound (Purchase/Restock)'), ('OUT', 'Outbound (Sales)'), ('ADJ', 'Stock Adjustment (Manual)'), ('TRF', 'Warehouse Transfer'), ('RET', 'Customer Return'), ('MPS', 'Marketplace Stock Reconciliation')], max_length=3),
        ),
    ]
