# Generated by Django 5.2.7 on 2026-06-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='variants/photos/'),
        ),
    ]
