# Generated by Django 5.2.7 on 2026-06-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_add_photo_to_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='last_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='last_unit_price_foreign',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
