# Generated by Django 5.2.7 on 2026-06-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_add_last_price_to_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='last_discounted_unit_price_foreign',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
