# Generated by Django 5.2.7 on 2026-06-29 12:05

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile'),
        ('inventory', '0022_productvariant_last_discounted_unit_price_foreign'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dim1_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dim1_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='dim2_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dim2_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ProductDimensionImage',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_dim_image_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('dim_key', models.CharField(max_length=100)),
                ('dim_value', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='variants/dimension_images/')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_images', to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'dim_key', 'dim_value')},
            },
        ),
    ]
