# Generated by Django 5.2.7 on 2026-07-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_noop_fk_refs"),
        (
            "inventory",
            "0025_remove_category_product_productphoto_productvariant_productvariantmarketplace",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="productbusinessentity",
                    name="product",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_entities",
                        to="catalog.product",
                    ),
                ),
                migrations.AlterField(
                    model_name="productcogs",
                    name="product_variant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.productvariant",
                    ),
                ),
                migrations.AlterField(
                    model_name="productdimensionimage",
                    name="product",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimension_images",
                        to="catalog.product",
                    ),
                ),
                migrations.AlterField(
                    model_name="productsupplier",
                    name="product",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_suppliers",
                        to="catalog.product",
                    ),
                ),
                migrations.AlterField(
                    model_name="productvariantwarehouse",
                    name="product_variant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_stocks",
                        to="catalog.productvariant",
                    ),
                ),
                migrations.AlterField(
                    model_name="stockmovement",
                    name="product_variant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.productvariant",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
