# Generated by Django 5.2.7 on 2026-07-08 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0026_noop_fk_refs"),
        ("tiktok", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="warehouse",
            table="master_warehouse",
        ),
    ]
