# Generated by Django 5.2.7 on 2026-07-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """State-only migration: register the ProductVariant compatibility proxy
    (apps.inventory.models.ProductVariant, based on catalog.ProductVariant) and
    repoint the inventory FK fields that still refer to it under the 'inventory'
    app label. Database tables/columns are unaffected (already owned by
    apps.catalog since inventory/0025 and catalog/0003)."""

    dependencies = [
        ("catalog", "0003_rename_master_tables"),
        ("inventory", "0027_rename_warehouse_table"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ProductVariant",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("catalog.productvariant",),
                ),
                migrations.AlterField(
                    model_name="productcogs",
                    name="product_variant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.productvariant",
                    ),
                ),
                migrations.AlterField(
                    model_name="productvariantwarehouse",
                    name="product_variant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_stocks",
                        to="inventory.productvariant",
                    ),
                ),
                migrations.AlterField(
                    model_name="stockmovement",
                    name="product_variant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.productvariant",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
