# Generated by Django 5.2.7 on 2026-08-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0032_state_only_retarget_productvariant_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcogs",
            name="allocated_commission_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Commission fee allocated per item total (IDR)",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="productcogs",
            name="allocated_delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Delivery fee allocated per unit (IDR)",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="productcogs",
            name="allocated_shipping_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Shipping fee allocated per unit (IDR)",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="productcogs",
            name="cogs_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Unit price in IDR = price_rmb * exchange_rate",
                max_digits=18,
            ),
        ),
    ]
