# Generated by Django 5.2.7 on 2026-08-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0033_alter_productcogs_allocated_commission_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcogs",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Exchange rate from PO at time of delivery (matches PurchaseOrder.exchange_rate precision)",
                max_digits=10,
            ),
        ),
    ]
