# Generated by Django 5.2.7 on 2026-04-27 07:47

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0005_add_allocated_fees_to_product_cogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopeeWebhookLog',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='webhook_log_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('shop_id', models.BigIntegerField(db_index=True)),
                ('event_code', models.IntegerField(db_index=True, help_text='Shopee webhook code (3=order, 4=item, etc.)')),
                ('payload', models.JSONField()),
                ('signature', models.CharField(blank=True, default='', max_length=512)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'shopee_webhook_log',
                'ordering': ['-cdate'],
            },
        ),
        migrations.CreateModel(
            name='ShopeeShop',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='shopee_shop_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('shop_id', models.BigIntegerField(help_text='Shopee shop_id', unique=True)),
                ('shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('partner_id', models.BigIntegerField(help_text='Shopee partner_id from App Console')),
                ('partner_key', models.CharField(help_text='Shopee partner_key (keep secret)', max_length=512)),
                ('access_token', models.CharField(blank=True, default='', max_length=512)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=512)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_order_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_product_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_stock_sync_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopee_shops', to='core.marketplace')),
            ],
            options={
                'db_table': 'shopee_shop',
            },
        ),
        migrations.CreateModel(
            name='ShopeeSyncLog',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='sync_log_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='running', max_length=20)),
                ('records_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='shopee.shopeeshop')),
            ],
            options={
                'db_table': 'shopee_sync_log',
                'ordering': ['-started_at'],
            },
        ),
    ]
