# Generated by Django 5.2.7 on 2026-05-22 20:02

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile'),
        ('inventory', '0006_category_master_category_key_productphoto'),
        ('shopee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopeeStockSyncLog',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='stock_sync_log_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('sku_variant_code', models.CharField(max_length=100)),
                ('quantity_synced', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sync_type', models.CharField(choices=[('FULL', 'Full Sync'), ('SINGLE', 'Single Variant')], default='SINGLE', max_length=10)),
                ('shopee_item_id', models.BigIntegerField(blank=True, null=True)),
                ('shopee_model_id', models.BigIntegerField(blank=True, null=True)),
                ('shopee_response', models.JSONField(default=dict)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sync_logs', to='shopee.shopeeshop')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopee_sync_logs', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['-cdate'],
                'indexes': [models.Index(fields=['shop', 'cdate'], name='shopee_shop_shop_id_ef4716_idx'), models.Index(fields=['variant', 'success'], name='shopee_shop_variant_1f6c3e_idx')],
            },
        ),
    ]
