# Generated by Django 5.2.7 on 2026-07-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_noop_fk_refs"),
        ("shopee", "0002_add_shopee_stock_sync_log"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="shopeestocksynclog",
                    name="variant",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopee_sync_logs",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
