# Generated by Django 5.2.7 on 2026-04-27 08:28

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0005_add_allocated_fees_to_product_cogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokShop',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='tiktok_shop_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('shop_id', models.CharField(help_text='TikTok shop_id', max_length=64, unique=True)),
                ('shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('app_key', models.CharField(help_text='TikTok App Key', max_length=128)),
                ('app_secret', models.CharField(help_text='TikTok App Secret (keep secret)', max_length=255)),
                ('access_token', models.CharField(blank=True, default='', max_length=512)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=512)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'tiktok_shop',
            },
        ),
        migrations.CreateModel(
            name='TikTokSyncLog',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='sync_log_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(max_length=32)),
                ('status', models.CharField(default='running', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('orders_synced', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='tiktok.tiktokshop')),
            ],
            options={
                'db_table': 'tiktok_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TikTokWebhookLog',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='webhook_log_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='tiktok.tiktokshop')),
            ],
            options={
                'db_table': 'tiktok_webhook_log',
                'ordering': ['-cdate'],
            },
        ),
    ]
