# Generated by Django 5.2.7 on 2026-07-08 07:35

import django_ulid.models
from django.db import migrations

import core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="category",
                    name="id",
                    field=django_ulid.models.ULIDField(
                        db_column="category_id",
                        default=core.utils.generate_ulid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="product",
                    name="id",
                    field=django_ulid.models.ULIDField(
                        db_column="product_id",
                        default=core.utils.generate_ulid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="productphoto",
                    name="id",
                    field=django_ulid.models.ULIDField(
                        db_column="product_photo_id",
                        default=core.utils.generate_ulid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="productvariant",
                    name="id",
                    field=django_ulid.models.ULIDField(
                        db_column="product_variant_id",
                        default=core.utils.generate_ulid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="productvariantmarketplace",
                    name="id",
                    field=django_ulid.models.ULIDField(
                        db_column="product_variant_marketplace_id",
                        default=core.utils.generate_ulid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
