# Generated by Django 5.2.7 on 2026-07-08 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_noop_fk_refs"),
        (
            "inventory",
            "0025_remove_category_product_productphoto_productvariant_productvariantmarketplace",
        ),
        ("inventory", "0026_noop_fk_refs"),
        ("purchasing", "0025_noop_fk_refs"),
        ("sales", "0004_noop_fk_refs"),
        ("shopee", "0003_noop_fk_refs"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="master_category",
        ),
        migrations.AlterModelTable(
            name="product",
            table="master_product",
        ),
        migrations.AlterModelTable(
            name="productphoto",
            table="master_productphoto",
        ),
        migrations.AlterModelTable(
            name="productvariant",
            table="master_productvariant",
        ),
        migrations.AlterModelTable(
            name="productvariantmarketplace",
            table="master_productvariantmarketplace",
        ),
        # Repoint trigger functions created in inventory/0024 and 0014
        # that hard-code old table names and would silently fail at runtime
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION generate_product_sku()
            RETURNS TRIGGER AS $$
            DECLARE
                cat_code TEXT;
                seq_val INT;
            BEGIN
                IF NEW.sku_code IS NULL OR NEW.sku_code = '' THEN
                    seq_val := nextval('product_sku_seq');
                    SELECT category_code INTO cat_code
                    FROM master_category WHERE category_id = NEW.category_id;
                    NEW.sku_code := UPPER(cat_code) || '-' || LPAD(seq_val::text, 3, '0');
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            CREATE OR REPLACE FUNCTION generate_product_sku()
            RETURNS TRIGGER AS $$
            DECLARE
                cat_code TEXT;
                seq_val INT;
            BEGIN
                IF NEW.sku_code IS NULL OR NEW.sku_code = '' THEN
                    seq_val := nextval('product_sku_seq');
                    SELECT category_code INTO cat_code
                    FROM inventory_category WHERE category_id = NEW.category_id;
                    NEW.sku_code := UPPER(cat_code) || '-' || LPAD(seq_val::text, 3, '0');
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION generate_variant_sku()
            RETURNS TRIGGER AS $$
            DECLARE
                parent_sku TEXT;
                sku_suffix TEXT;
            BEGIN
                IF NEW.sku_variant_code IS NULL OR NEW.sku_variant_code = '' THEN
                    SELECT sku_code INTO parent_sku
                    FROM master_product WHERE product_id = NEW.product_id;

                    NEW.sku_variant_code := parent_sku;

                    SELECT string_agg(UPPER(value), '-' ORDER BY key) INTO sku_suffix
                    FROM jsonb_each_text(NEW.variant_values::jsonb);

                    IF sku_suffix IS NOT NULL AND sku_suffix != '' THEN
                        NEW.sku_variant_code := NEW.sku_variant_code || '-' || sku_suffix;
                    END IF;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            CREATE OR REPLACE FUNCTION generate_variant_sku()
            RETURNS TRIGGER AS $$
            DECLARE
                parent_sku TEXT;
                sku_suffix TEXT;
            BEGIN
                IF NEW.sku_variant_code IS NULL OR NEW.sku_variant_code = '' THEN
                    SELECT sku_code INTO parent_sku
                    FROM inventory_product WHERE product_id = NEW.product_id;

                    NEW.sku_variant_code := parent_sku;

                    SELECT string_agg(UPPER(value), '-' ORDER BY key) INTO sku_suffix
                    FROM jsonb_each_text(NEW.variant_values::jsonb);

                    IF sku_suffix IS NOT NULL AND sku_suffix != '' THEN
                        NEW.sku_variant_code := NEW.sku_variant_code || '-' || sku_suffix;
                    END IF;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
        ),
    ]
