# Generated by Django 5.2.7 on 2026-08-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_state_only_create_productdimensionimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="current_cogs",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="productvariantmarketplace",
            name="discounted_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="productvariantmarketplace",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
